name: Kasio Release Pipeline

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build Standalone JAR
      run: ./gradlew fatJar

    - name: Publish GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        files: app/build/libs/Kasio-*-standalone.jar
        generate_release_notes: true